abbr -a -- d-c 'docker compose'
abbr -a -- d-cb 'docker compose build'
abbr -a -- d-cc 'docker compose config'
abbr -a -- d-cd 'docker compose down'
abbr -a -- d-cdb 'docker compose -f docker-compose.yml -f .devcontainer/docker-compose.yml build'
abbr -a -- d-cdc 'docker compose -f docker-compose.yml -f .devcontainer/docker-compose.yml config'
abbr -a -- d-cl 'docker compose ls -a'
abbr -a -- d-cr 'docker compose run --rm'
abbr -a -- d-cs 'docker compose stop'
abbr -a -- d-cu 'docker compose up'
abbr -a -- db 'docker build'
abbr -a -- dc 'docker container'
abbr -a -- dcl 'docker container ls -a'
abbr -a -- dcr 'docker container run -it --rm'
abbr -a -- dih 'docker image history'
abbr -a -- dil 'docker image ls -a'
abbr -a -- dir 'docker image rm'
abbr -a -- dnl 'docker network ls'
abbr -a -- dnr 'docker network rm'
abbr -a -- dvl 'docker volume ls'
abbr -a -- dvr 'docker volume rm'
abbr -a -- ga 'git add'
abbr -a -- ga. 'git add .'
abbr -a -- ga.c 'git add . && git commit'
abbr -a -- gap 'git add -p'
abbr -a -- gbr 'git branch'
abbr -a -- gbrd 'git branch --delete'
abbr -a -- gbrdf 'git branch --delete --force'
abbr -a -- gbrf 'git branch --force'
abbr -a -- gc 'git commit'
abbr -a -- gca 'git commit --amend'
abbr -a -- gcf 'git commit --fixup'
abbr -a -- gcm 'git commit -m'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gcpa 'git cherry-pick --abort'
abbr -a -- gcpc 'git cherry-pick --continue'
abbr -a -- gd 'git diff'
abbr -a -- gdc 'git diff --cached'
abbr -a -- gf 'git fetch'
abbr -a -- gl 'git log --graph --decorate --all --oneline'
abbr -a -- gm 'git merge'
abbr -a -- gmf 'git merge --ff-only'
abbr -a -- gmn 'git merge --no-ff'
abbr -a -- gpl 'git pull'
abbr -a -- gplr 'git pull --rebase'
abbr -a -- gplrod 'git pull --rebase origin develop'
abbr -a -- gps 'git push'
abbr -a -- gpsf 'git push --force-with-lease --force-if-includes'
abbr -a -- grb 'git rebase'
abbr -a -- grba 'git rebase --abort'
abbr -a -- grbc 'git rebase --continue'
abbr -a -- grbd 'git rebase develop'
abbr -a -- grbi 'git rebase -i'
abbr -a -- grbir 'git rebase -i --root'
abbr -a -- grm 'git rm'
abbr -a -- grss 'git restore --staged'
abbr -a -- grsw 'git restore --worktree'
abbr -a -- grt 'git reset'
abbr -a -- grth 'git reset --hard'
abbr -a -- grtho 'git reset --hard ORIG_HEAD'
abbr -a -- gs 'git status'
abbr -a -- gsh 'git stash'
abbr -a -- gsha 'git stash apply'
abbr -a -- gshc 'git stash clear'
abbr -a -- gshd 'git stash drop'
abbr -a -- gshk 'git stash --keep-index'
abbr -a -- gshp 'git stash pop'
abbr -a -- gshs 'git stash --staged'
abbr -a -- gsw 'git switch'
abbr -a -- gswc 'git switch --create'
abbr -a -- gswcf 'git switch --force-create'
abbr -a -- gswd 'git switch --detach'
abbr -a -- gwa 'git worktree add'
abbr -a -- gwab 'git worktree add -b'
abbr -a -- gwl 'git worktree list'
abbr -a -- gwr 'git worktree remove'
abbr -a -- ll 'eza -lha'
